### ISSUE TITLE
Error when trying to create simulatedMotionSensor

### ISSUE THREAD

**Issue by actionplant** [MikeMaxwell/zmm#2]
Zone Motion Manager and zoneMotionChild install with no errors, but when trying to create a new app and copying the raw code for the simulatedMotionSensor, I get the following error: 

No signature of method: script1509034271221842958676.metadata() is applicable for argument types: (script1509034271221842958676$_run_closure1) values: [script1509034271221842958676$_run_closure1@68baa5bd] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by MikeMaxwell** [comment]
did you install and publish the code for simulatedMotionSensor in "My Device Handlers"?
simulatedMotionSensor is a virtual device (a device handler), not an app.

**Comment by actionplant** [comment]
I'm an idiot. This is what happens when I try to tinker when I take a sick day and should be in bed. My apologies.
